name: CI for Transformer Tutorials

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert jupyter_client ipykernel
        # Add other dependencies here, for example:
        pip install -r requirements.txt

    - name: Execute Notebooks
      run: |
        find ./notebooks -name "*.ipynb" -exec jupyter nbconvert --to notebook --execute {} \;
