name: Test Changed Notebooks

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.ipynb'

jobs:
  test-notebooks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensures the entire git history is checked out

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert ipykernel
        # Add any additional dependencies here

    - name: Find Added or Modified Notebooks
      id: find-notebooks
      run: |
        echo "Added or Modified notebooks:"
        git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} '**/*.ipynb' | tee changed_notebooks.txt
        if [[ -s changed_notebooks.txt ]]; then
          echo "::set-output name=has_changes::true"
        else
          echo "::set-output name=has_changes::false"
        fi

    - name: Execute Notebooks
      if: steps.find-notebooks.outputs.has_changes == 'true'
      run: |
        while IFS= read -r notebook; do
          jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=600 "$notebook"
        done < changed_notebooks.txt
