name: Python Notebook CI

on:
  push:
    branches: [ main ]
    paths:
      - 'notebooks/**/*.ipynb'
  pull_request:
    branches: [ main ]
    paths:
      - 'notebooks/**/*.ipynb'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          !~/.cache/pip/log
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute Notebooks
      run: |
        find ./notebooks -name "*.ipynb" -exec jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=600 {} \;
